CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = 32000
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

LLAVA_IGNORE_INDEX = -100
LLAVA_DEFAULT_IMAGE_PATCH_TOKEN_IDX = 32000
LLAVA_DEFAULT_IMAGE_TOKEN = "<image>"
LLAVA_DEFAULT_IM_TOKEN_PLACE_HOLDER = "<image>"
LLAVA_DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
LLAVA_DEFAULT_IM_START_TOKEN = "<im_start>"
LLAVA_DEFAULT_IM_END_TOKEN = "<im_end>"